// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnenoqhsgldoknpmcqzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZW5vcWhzZ2xkb2tucG1jcXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODg4ODIsImV4cCI6MjA3MTI2NDg4Mn0.vHU14FwUhFZnBc_57pvzMZ0SfNSgwFG88BYiW7b5KIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});